export default [
  ["web application", ["cms", "crm", "pwa", "website", "seo"]],
  [
    "knowledge",
    [
      "react",
      "react native",
      "nextjs",
      "muxtjs",
      "vuejs",
      "python",
      "spring boot",
      "django",
      "fastapi",
      "laravel",
      "strapi",
      "wordpress",
      "mexal",
      "apollo",
      "graphql",
      "passweb",
      "kafka",
      "mqtt",
      "lua",
      "python",
      "java",
      ".net core",
      "php",
      "swift",
      "docker",
      "kubernates",
      "nodejs",
      "l-pic linux system",
      "aws",
      "google Cloud computing",
      "wmware",
      "stl",
      "3d moddeling",
      "cad designer",
    ],
  ],
  [
    "services IOT / automation",
    [
      "projectation",
      "microcontroller",
      "access mointoring",
      "mqtt",
      "payment system",
      "industrial machine-to-machine communication",
    ],
  ],
  [
    "networking",
    [
      "manegment",
      "nas",
      "switching and routing",
      "cisco certified",
      "video surveillance",
      "system monitoring",
      "cloud",
      "server managment",
    ],
  ],
  [
    "architectural / engineering",
    [
      "full stack engineer",
      "backend",
      "frontend",
      "data lake",
      "monolitic standard",
      "microcervices",
      "kafka",
      "devops",
      "cloud",
    ],
  ],
];
